# Source code in this file is inherited from
# "pronto-action" https://github.com/HeRoMo/pronto-action
# MIT License | Copyright (c) 2019 HeRoMo
# see https://opensource.org/licenses/MIT

# and modified by
# MIT License | Copyright (c) 2021 Syuparn

name: Publish Docker image
on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io
          repository: syuparn/webawk
          tag_with_ref: true
