name: Test

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out repo directory
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt update -y && sudo apt install -y gawk jq

    - name: AwkTest
      run: ./test.sh
